#!/usr/bin/env bash
# AIVAN Bootstrap (Linux / macOS)
# Sets up a local development environment from scratch.
set -euo pipefail

echo "=== AIVAN Bootstrap (Linux/macOS) ==="
echo ""

# ------------------------------------------------------------------
# 1. Check uv is available
# ------------------------------------------------------------------
if ! command -v uv &>/dev/null; then
    echo "[ERROR] 'uv' is not installed."
    echo "  Install it with:"
    echo "    curl -Ls https://astral.sh/uv/install.sh | sh"
    echo "  Or: pip install uv"
    exit 1
fi
echo "[OK] uv found: $(uv --version)"

# ------------------------------------------------------------------
# 2. Copy .env.example → .env if .env does not exist
# ------------------------------------------------------------------
if [ ! -f ".env" ]; then
    if [ -f ".env.example" ]; then
        cp .env.example .env
        echo "[OK] Copied .env.example → .env"
        echo "  Review .env and fill in any required API keys before running AIVAN."
    else
        echo "[WARN] No .env.example found. Creating a minimal .env with mock settings."
        cat > .env <<'EOF'
# AIVAN local environment — generated by bootstrap_local.sh
AIVAN_LLM_PROVIDER=mock
OPENCLAW_MOCK_MODE=true
AIVAN_DB_URL=sqlite:///./data/aivan.db
AIVAN_HOST=127.0.0.1
AIVAN_PORT=8765
EOF
        echo "[OK] Created minimal .env (mock mode)"
    fi
else
    echo "[OK] .env already exists — skipping copy"
fi

# ------------------------------------------------------------------
# 3. Install Python dependencies via uv
# ------------------------------------------------------------------
echo ""
echo "[...] Installing dependencies (uv sync)..."
uv sync
echo "[OK] Dependencies installed"

# ------------------------------------------------------------------
# 4. Initialize AIVAN database and platform registry
# ------------------------------------------------------------------
echo ""
echo "[...] Initializing AIVAN (database + platform whitelist)..."
uv run aivan init
echo "[OK] AIVAN initialized"

# ------------------------------------------------------------------
# 5. Optional: import sample data
# ------------------------------------------------------------------
echo ""
if [ -f "data/sample_suppliers.csv" ]; then
    echo "[...] Importing sample suppliers from data/sample_suppliers.csv..."
    uv run aivan import-suppliers data/sample_suppliers.csv
    echo "[OK] Sample suppliers imported"
else
    echo "[SKIP] data/sample_suppliers.csv not found — skipping import"
fi

# ------------------------------------------------------------------
# Done
# ------------------------------------------------------------------
echo ""
echo "=== Bootstrap complete ==="
echo ""
echo "  Run the demo          : uv run aivan demo"
echo "  Run marketplace demo  : uv run aivan demo-marketplace"
echo "  Start local server    : uv run aivan serve"
echo "  Run E2E scripts       : uv run python scripts/run_aivan_e2e.py"
echo ""
